modes:
 resimulation: no
 fitness: global
 airspace: saved            # saved, generated
 traffic: deterministic     # deterministic, probabilistic, constant
 prob_record: false         # true, false
 position: random           # random, constant
 agent: link                # sector, link
 search: astar              # astar, rags, quick
 square: false              # true, false
 objective: travel_time     # delay, conflicts, travel_time
 disposal: trash            # keep, trash
 types: false               # false -- don't use type, true -- do use types
 numbered_domain: false     # true, false
 destinations: static       # random, static
 destination: list          # all, list
 generation: list           # all, list
 capacity: list             # flat, list
 state: traffic             # traffic -- state is only traffic thru link, incoming -- traffic + incomming uavs from other links as second state
 tracking: true            # true, false
 tracking_type: first_last # all -- store all epochs, first_last -- store first and last epochs of final stat run [ONLY READ IN IF "tracking: true"]
 window_mode: variable 	# cumulative (window_size = steps), variable (window_size specified below)
neuroevo:
 popsize: 10
 nn:
  gamma: 0.9
  eta: 0.1
  mut_rate: 0.1
  mut_std: 1.0
  layers: 1
  sigmoid_output: true
  hidden: 20
  input: 1                  # if {agent: sector, input: 4}, else if {agent: link, input: 1}
  output: 1                 # if {agent: sector, output: 4}, else if {agent: link, output: 1}

approximator:
 nn:
  gamma: 0.9
  eta: 0.1
  mut_rate: 0.1
  mut_std: 1.0
  layers: 1
  sigmoid_output: false
  hidden: 20
  input: 4
  output: 1

time:
 epochs: 3
 trials: 1
 steps: 3
 runs: 2

constants:
 sectors: 11
 alpha: 8.4852813742385702928101323452582
 capacity: 2
# vehicles: 10
 generation_probability: 0.33
 generation_rate: 3
# arrival_threshold: 1
# conflict_threshold: 1
 num_generated: 5
 window_size: 0 # used by links to record how many UAVs passed through which other links; if set to 0, this feature is not used
 xdim: 10
 ydim: 10


# Denotes the speed for each type
# types:
# slow: 1
# fast: 2
